"use client";

import { useState, useMemo } from "react";
import {
  AI_MODELS,
  calculateTokenCost,
  getTokenCostExplanationSteps,
  countWordsFromText,
  estimateTokensFromWords,
  formatCurrencyDetailed,
  formatCurrencyStandard,
  TokenCostResult,
} from "@/lib/calculators/aiTokenCost";
import { generatePdfAsync } from "@/lib/utils/downloadPdf";
import DownloadPdfButton from "@/components/DownloadPdfButton";
import ExplainResultAccordion from "@/components/ExplainResultAccordion";
import ShareResultButton from "@/components/ShareResultButton";
import ShareResultModal from "@/components/ShareResultModal";
import { Cpu, Zap, Calculator, ArrowRightLeft, DollarSign, Layers, Check, Info, FileText } from "lucide-react";

export default function AITokenCostWidget() {
  const [modelId, setModelId] = useState<string>("gpt-4o");
  const [customInputRate, setCustomInputRate] = useState<number>(1.00);
  const [customOutputRate, setCustomOutputRate] = useState<number>(3.00);

  const [inputMode, setInputMode] = useState<"tokens" | "words">("tokens");
  
  // Direct Token State
  const [inputTokens, setInputTokens] = useState<number>(1000);
  const [outputTokens, setOutputTokens] = useState<number>(500);

  // Word / Text Estimation State
  const [inputText, setInputText] = useState<string>("");
  const [outputText, setOutputText] = useState<string>("");
  const [inputWords, setInputWords] = useState<number>(750);
  const [outputWords, setOutputWords] = useState<number>(375);

  // Volume State
  const [requestsPerDay, setRequestsPerDay] = useState<number>(1000);

  const [copied, setCopied] = useState<boolean>(false);
  const [isShareModalOpen, setIsShareModalOpen] = useState<boolean>(false);
  const [isPdfLoading, setIsPdfLoading] = useState<boolean>(false);

  // Effective tokens based on active mode
  const effectiveInputTokens = useMemo(() => {
    if (inputMode === "tokens") return inputTokens;
    if (inputText.trim()) {
      const words = countWordsFromText(inputText);
      return estimateTokensFromWords(words);
    }
    return estimateTokensFromWords(inputWords);
  }, [inputMode, inputTokens, inputText, inputWords]);

  const effectiveOutputTokens = useMemo(() => {
    if (inputMode === "tokens") return outputTokens;
    if (outputText.trim()) {
      const words = countWordsFromText(outputText);
      return estimateTokensFromWords(words);
    }
    return estimateTokensFromWords(outputWords);
  }, [inputMode, outputTokens, outputText, outputWords]);

  // Compute full result
  const result: TokenCostResult = useMemo(() => {
    return calculateTokenCost(
      modelId,
      effectiveInputTokens,
      effectiveOutputTokens,
      requestsPerDay,
      customInputRate,
      customOutputRate
    );
  }, [modelId, effectiveInputTokens, effectiveOutputTokens, requestsPerDay, customInputRate, customOutputRate]);

  const handleCopy = () => {
    const text = [
      `🤖 AI Token Cost Calculation (${result.selectedModel.name})`,
      `• Cost per Request: ${formatCurrencyDetailed(result.costPerRequest)}`,
      `• Projected Monthly Cost: ${formatCurrencyStandard(result.monthlyTotalCost)} (${result.requestsPerMonth.toLocaleString()} calls/mo)`,
      `• Input Tokens: ${result.inputTokens.toLocaleString()} ($${result.selectedModel.inputCostPerM}/1M)`,
      `• Output Tokens: ${result.outputTokens.toLocaleString()} ($${result.selectedModel.outputCostPerM}/1M)`,
      `Calculated on QuickCalc: https://quickcalc.cloud/tools/ai-token-cost-calculator`,
    ].join("\n");

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleExportTxt = () => {
    const text = [
      `AI TOKEN COST CALCULATOR REPORT`,
      `Generated by QuickCalc (https://quickcalc.cloud)`,
      `--------------------------------------------------`,
      `Selected Model: ${result.selectedModel.name} (${result.selectedModel.provider})`,
      `Pricing Rates: $${result.selectedModel.inputCostPerM}/1M Input | $${result.selectedModel.outputCostPerM}/1M Output`,
      `--------------------------------------------------`,
      `Input Tokens / Request: ${result.inputTokens.toLocaleString()}`,
      `Output Tokens / Request: ${result.outputTokens.toLocaleString()}`,
      `Total Tokens / Request: ${result.totalTokensPerRequest.toLocaleString()}`,
      `--------------------------------------------------`,
      `Cost per Single Request: ${formatCurrencyDetailed(result.costPerRequest)}`,
      `Cost per 1,000 Requests: ${formatCurrencyStandard(result.costPer1kRequests)}`,
      `Projected Daily Cost: ${formatCurrencyStandard(result.costPerRequest * result.requestsPerDay)}`,
      `Projected Monthly Cost: ${formatCurrencyStandard(result.monthlyTotalCost)} (${result.requestsPerMonth.toLocaleString()} calls)`,
      `Projected Annual Cost: ${formatCurrencyStandard(result.annualTotalCost)}`,
      `--------------------------------------------------`,
      `Top Model Price Comparison for this Workload:`,
      ...result.comparisons.map(
        (c) => ` - ${c.modelName} (${c.provider}): ${formatCurrencyDetailed(c.costPerRequest)} / req | ${formatCurrencyStandard(c.monthlyCost)} / mo`
      ),
      `--------------------------------------------------`,
      `Pricing Last Checked: August 2026. Prices are estimates for comparison.`,
    ].join("\n");

    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `ai-token-cost-${result.selectedModel.name.replace(/[^a-zA-Z0-9]/g, "-")}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = async () => {
    setIsPdfLoading(true);
    try {
      await generatePdfAsync({
        toolName: "AI Token Cost Calculator",
        toolSlug: "ai-token-cost-calculator",
        inputs: [
          { label: "AI Model", value: `${result.selectedModel.name} (${result.selectedModel.provider})` },
          { label: "Input Tokens", value: result.inputTokens.toLocaleString() },
          { label: "Output Tokens", value: result.outputTokens.toLocaleString() },
          { label: "Daily API Calls", value: result.requestsPerDay.toLocaleString() },
        ],
        results: [
          { label: "Cost Per Single Request", value: formatCurrencyDetailed(result.costPerRequest), isHighlight: true },
          { label: "Projected Monthly Cost", value: formatCurrencyStandard(result.monthlyTotalCost), isHighlight: true },
          { label: "Cost Per 1,000 Calls", value: formatCurrencyStandard(result.costPer1kRequests) },
          { label: "Projected Annual Cost", value: formatCurrencyStandard(result.annualTotalCost) },
        ],
        summaryNote: `Pricing rates last referenced August 2026 ($${result.selectedModel.inputCostPerM}/1M in, $${result.selectedModel.outputCostPerM}/1M out).`,
        table: {
          title: "Side-by-Side Model Cost Comparison for Same Workload",
          headers: ["Model", "Provider", "Cost / Request", "Monthly Cost"],
          rows: result.comparisons.map((c) => [
            c.modelName,
            c.provider,
            formatCurrencyDetailed(c.costPerRequest),
            formatCurrencyStandard(c.monthlyCost),
          ]),
        },
        filename: `AI-Token-Cost-Report.pdf`,
      });
    } finally {
      setIsPdfLoading(false);
    }
  };

  const explanationSteps = useMemo(() => {
    return getTokenCostExplanationSteps(result);
  }, [result]);

  return (
    <div className="w-full max-w-3xl mx-auto bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl shadow-xl overflow-hidden my-6 transition-all">
      
      {/* TOOL INPUT CONTROLS */}
      <div className="p-4 sm:p-6 space-y-6 border-b border-zinc-200 dark:border-zinc-800 bg-zinc-50/50 dark:bg-zinc-950/30">
        
        {/* Model Selection Dropdown & Rates */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <label htmlFor="modelSelect" className="block text-xs font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
              1. Select AI Model & Provider
            </label>
            <span className="text-[11px] font-medium text-teal-600 dark:text-teal-400">
              Rates per 1M tokens
            </span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-12 gap-3">
            <select
              id="modelSelect"
              value={modelId}
              onChange={(e) => setModelId(e.target.value)}
              className="sm:col-span-8 rounded-xl border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-800 px-3.5 py-2.5 text-sm font-semibold text-zinc-900 dark:text-white focus:border-teal-500 focus:outline-none focus:ring-1 focus:ring-teal-500 shadow-sm"
            >
              {AI_MODELS.map((m) => (
                <option key={m.id} value={m.id}>
                  {m.name} ({m.provider}) — ${m.inputCostPerM}/1M in, ${m.outputCostPerM}/1M out
                </option>
              ))}
            </select>

            {/* Price Preview Chip */}
            <div className="sm:col-span-4 bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-xl px-3 py-2 flex items-center justify-around text-xs font-mono shadow-xs">
              <div>
                <span className="text-[10px] text-zinc-400 block font-sans">Input / 1M</span>
                <span className="font-bold text-teal-600 dark:text-teal-400">
                  ${result.selectedModel.inputCostPerM}
                </span>
              </div>
              <div className="h-6 w-px bg-zinc-200 dark:bg-zinc-700"></div>
              <div>
                <span className="text-[10px] text-zinc-400 block font-sans">Output / 1M</span>
                <span className="font-bold text-emerald-600 dark:text-emerald-400">
                  ${result.selectedModel.outputCostPerM}
                </span>
              </div>
            </div>
          </div>

          {/* Custom Model Rates Inputs */}
          {modelId === "custom" && (
            <div className="p-3.5 bg-white dark:bg-zinc-800/90 rounded-xl border border-zinc-200 dark:border-zinc-700 grid grid-cols-2 gap-3 animate-fade-in">
              <div>
                <label className="block text-xs font-medium text-zinc-600 dark:text-zinc-300 mb-1">
                  Custom Input Rate ($/1M tokens)
                </label>
                <input
                  type="number"
                  step="any"
                  min="0"
                  value={customInputRate}
                  onChange={(e) => setCustomInputRate(parseFloat(e.target.value) || 0)}
                  className="w-full rounded-lg border border-zinc-300 dark:border-zinc-700 px-3 py-1.5 text-xs font-mono bg-transparent"
                />
              </div>
              <div>
                <label className="block text-xs font-medium text-zinc-600 dark:text-zinc-300 mb-1">
                  Custom Output Rate ($/1M tokens)
                </label>
                <input
                  type="number"
                  step="any"
                  min="0"
                  value={customOutputRate}
                  onChange={(e) => setCustomOutputRate(parseFloat(e.target.value) || 0)}
                  className="w-full rounded-lg border border-zinc-300 dark:border-zinc-700 px-3 py-1.5 text-xs font-mono bg-transparent"
                />
              </div>
            </div>
          )}
        </div>

        {/* Input Mode Switcher (Tokens vs Text/Words) */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label className="block text-xs font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
              2. Input & Output Token Volume
            </label>
            <div className="inline-flex rounded-lg p-0.5 bg-zinc-200 dark:bg-zinc-800 text-xs font-semibold">
              <button
                type="button"
                onClick={() => setInputMode("tokens")}
                className={`px-2.5 py-1 rounded-md transition-all ${
                  inputMode === "tokens"
                    ? "bg-white dark:bg-zinc-900 text-teal-600 dark:text-teal-400 shadow-xs"
                    : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900"
                }`}
              >
                Exact Token Counts
              </button>
              <button
                type="button"
                onClick={() => setInputMode("words")}
                className={`px-2.5 py-1 rounded-md transition-all ${
                  inputMode === "words"
                    ? "bg-white dark:bg-zinc-900 text-teal-600 dark:text-teal-400 shadow-xs"
                    : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900"
                }`}
              >
                Text / Word Estimator
              </button>
            </div>
          </div>

          {inputMode === "tokens" ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label htmlFor="inputTokens" className="block text-xs font-medium text-zinc-700 dark:text-zinc-300 mb-1">
                  Input Tokens (Prompt + Context)
                </label>
                <div className="flex rounded-xl shadow-xs border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-800 overflow-hidden">
                  <input
                    id="inputTokens"
                    type="number"
                    min="0"
                    step="100"
                    value={inputTokens}
                    onChange={(e) => setInputTokens(parseInt(e.target.value, 10) || 0)}
                    className="w-full px-3.5 py-2.5 text-sm font-semibold font-mono text-zinc-900 dark:text-white bg-transparent focus:outline-none"
                  />
                  <span className="px-3 py-2.5 bg-zinc-100 dark:bg-zinc-700 text-xs text-zinc-500 font-sans flex items-center">
                    tokens
                  </span>
                </div>
                <span className="text-[11px] text-zinc-400 mt-1 block">
                  ~{Math.round(inputTokens * 0.75)} words
                </span>
              </div>

              <div>
                <label htmlFor="outputTokens" className="block text-xs font-medium text-zinc-700 dark:text-zinc-300 mb-1">
                  Output Tokens (Completion Response)
                </label>
                <div className="flex rounded-xl shadow-xs border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-800 overflow-hidden">
                  <input
                    id="outputTokens"
                    type="number"
                    min="0"
                    step="50"
                    value={outputTokens}
                    onChange={(e) => setOutputTokens(parseInt(e.target.value, 10) || 0)}
                    className="w-full px-3.5 py-2.5 text-sm font-semibold font-mono text-zinc-900 dark:text-white bg-transparent focus:outline-none"
                  />
                  <span className="px-3 py-2.5 bg-zinc-100 dark:bg-zinc-700 text-xs text-zinc-500 font-sans flex items-center">
                    tokens
                  </span>
                </div>
                <span className="text-[11px] text-zinc-400 mt-1 block">
                  ~{Math.round(outputTokens * 0.75)} words
                </span>
              </div>
            </div>
          ) : (
            <div className="space-y-3 p-3.5 bg-white dark:bg-zinc-800/80 rounded-xl border border-zinc-200 dark:border-zinc-700">
              <div className="text-[11px] text-teal-700 dark:text-teal-300 bg-teal-50 dark:bg-teal-950/40 p-2 rounded-lg flex items-center gap-1.5">
                <Info size={14} className="shrink-0" />
                <span>Text conversion uses standard ratio of <strong>~0.75 words per token</strong> (1 word ≈ 1.33 tokens).</span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label htmlFor="inputWords" className="block text-xs font-medium text-zinc-700 dark:text-zinc-300 mb-1">
                    Input Word Count (or paste prompt)
                  </label>
                  <input
                    type="number"
                    id="inputWords"
                    min="0"
                    value={inputWords}
                    onChange={(e) => {
                      setInputWords(parseInt(e.target.value, 10) || 0);
                      setInputText("");
                    }}
                    className="w-full rounded-lg border border-zinc-300 dark:border-zinc-700 px-3 py-2 text-xs font-mono bg-transparent mb-1.5"
                    placeholder="Word count e.g. 750"
                  />
                  <textarea
                    rows={2}
                    placeholder="Or paste input prompt text here..."
                    value={inputText}
                    onChange={(e) => setInputText(e.target.value)}
                    className="w-full rounded-lg border border-zinc-200 dark:border-zinc-700 p-2 text-xs bg-zinc-50 dark:bg-zinc-900 focus:outline-none"
                  ></textarea>
                  <span className="text-[11px] font-semibold text-teal-600 dark:text-teal-400 block mt-0.5">
                    Calculated: {effectiveInputTokens.toLocaleString()} input tokens
                  </span>
                </div>

                <div>
                  <label htmlFor="outputWords" className="block text-xs font-medium text-zinc-700 dark:text-zinc-300 mb-1">
                    Output Word Count (or paste response)
                  </label>
                  <input
                    type="number"
                    id="outputWords"
                    min="0"
                    value={outputWords}
                    onChange={(e) => {
                      setOutputWords(parseInt(e.target.value, 10) || 0);
                      setOutputText("");
                    }}
                    className="w-full rounded-lg border border-zinc-300 dark:border-zinc-700 px-3 py-2 text-xs font-mono bg-transparent mb-1.5"
                    placeholder="Word count e.g. 375"
                  />
                  <textarea
                    rows={2}
                    placeholder="Or paste output response text here..."
                    value={outputText}
                    onChange={(e) => setOutputText(e.target.value)}
                    className="w-full rounded-lg border border-zinc-200 dark:border-zinc-700 p-2 text-xs bg-zinc-50 dark:bg-zinc-900 focus:outline-none"
                  ></textarea>
                  <span className="text-[11px] font-semibold text-emerald-600 dark:text-emerald-400 block mt-0.5">
                    Calculated: {effectiveOutputTokens.toLocaleString()} output tokens
                  </span>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Requests Frequency / Volume */}
        <div>
          <label htmlFor="reqPerDay" className="block text-xs font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400 mb-2">
            3. API Request Frequency & Monthly Volume
          </label>
          <div className="flex flex-col sm:flex-row gap-3 items-stretch sm:items-center">
            <div className="flex-1 flex rounded-xl shadow-xs border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-800 overflow-hidden">
              <input
                id="reqPerDay"
                type="number"
                min="1"
                value={requestsPerDay}
                onChange={(e) => setRequestsPerDay(parseInt(e.target.value, 10) || 0)}
                className="w-full px-3.5 py-2.5 text-sm font-semibold font-mono text-zinc-900 dark:text-white bg-transparent focus:outline-none"
              />
              <span className="px-3 py-2.5 bg-zinc-100 dark:bg-zinc-700 text-xs text-zinc-500 font-sans flex items-center shrink-0">
                calls / day
              </span>
            </div>

            {/* Quick Volume Preset Chips */}
            <div className="flex items-center gap-1.5 flex-wrap">
              {[100, 1000, 5000, 25000].map((v) => (
                <button
                  key={v}
                  type="button"
                  onClick={() => setRequestsPerDay(v)}
                  className={`px-2.5 py-1 rounded-lg text-xs font-medium transition-colors border ${
                    requestsPerDay === v
                      ? "bg-teal-50 dark:bg-teal-950/40 text-teal-700 dark:text-teal-300 border-teal-300 dark:border-teal-700"
                      : "bg-white dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 border-zinc-200 dark:border-zinc-700 hover:bg-zinc-100 dark:hover:bg-zinc-700"
                  }`}
                >
                  {v >= 1000 ? `${v / 1000}k/day` : `${v}/day`}
                </button>
              ))}
            </div>
          </div>
          <span className="text-[11px] text-zinc-400 mt-1 block">
            = <strong>{result.requestsPerMonth.toLocaleString()}</strong> requests / month
          </span>
        </div>

      </div>

      {/* RESULTS DISPLAY */}
      <div className="p-4 sm:p-6 space-y-6">
        
        {/* HERO COST CARDS */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
          
          {/* Main Card: Cost per Request */}
          <div className="md:col-span-6 p-5 rounded-2xl bg-gradient-to-br from-teal-950/90 via-zinc-900 to-emerald-950 text-white border border-teal-800/50 shadow-lg space-y-2">
            <span className="text-xs uppercase tracking-wider text-teal-300 font-bold block">
              Cost Per Single API Request
            </span>
            <div className="font-mono text-4xl sm:text-5xl font-extrabold tracking-tight text-white tabular-nums drop-shadow-md">
              {formatCurrencyDetailed(result.costPerRequest)}
            </div>
            <div className="text-xs text-zinc-300 pt-2 border-t border-white/10 flex justify-between">
              <span>Input: <strong>{formatCurrencyDetailed(result.inputCostPerRequest)}</strong></span>
              <span>Output: <strong>{formatCurrencyDetailed(result.outputCostPerRequest)}</strong></span>
            </div>
          </div>

          {/* Secondary Cards: Monthly & 1k Calls */}
          <div className="md:col-span-6 grid grid-cols-2 gap-3">
            <div className="p-4 rounded-2xl bg-zinc-50 dark:bg-zinc-950/60 border border-zinc-200 dark:border-zinc-800 space-y-1 flex flex-col justify-between">
              <span className="text-[11px] uppercase tracking-wider text-zinc-500 font-bold block">
                Projected Monthly
              </span>
              <div className="font-mono text-2xl sm:text-3xl font-extrabold text-zinc-900 dark:text-white tabular-nums">
                {formatCurrencyStandard(result.monthlyTotalCost)}
              </div>
              <span className="text-[10px] text-zinc-400 font-medium">
                {result.requestsPerMonth.toLocaleString()} calls / mo
              </span>
            </div>

            <div className="p-4 rounded-2xl bg-zinc-50 dark:bg-zinc-950/60 border border-zinc-200 dark:border-zinc-800 space-y-1 flex flex-col justify-between">
              <span className="text-[11px] uppercase tracking-wider text-zinc-500 font-bold block">
                Cost Per 1k Calls
              </span>
              <div className="font-mono text-2xl sm:text-3xl font-extrabold text-zinc-900 dark:text-white tabular-nums">
                {formatCurrencyStandard(result.costPer1kRequests)}
              </div>
              <span className="text-[10px] text-zinc-400 font-medium">
                Annual: {formatCurrencyStandard(result.annualTotalCost)}
              </span>
            </div>
          </div>

        </div>

        {/* SIDE-BY-SIDE MODEL COMPARISON GRID (KEY UNIQUE FEATURE) */}
        <div className="p-4 sm:p-5 bg-zinc-50 dark:bg-zinc-950/50 border border-zinc-200 dark:border-zinc-800 rounded-2xl space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <ArrowRightLeft size={16} className="text-teal-600 dark:text-teal-400" />
              <span className="text-xs font-bold uppercase tracking-wider text-zinc-900 dark:text-zinc-100">
                Side-by-Side Model Cost Comparison (Same Workload)
              </span>
            </div>
            <span className="text-[11px] text-zinc-400 font-medium hidden sm:inline">
              {result.totalTokensPerRequest.toLocaleString()} tokens / call
            </span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-zinc-200 dark:border-zinc-800 text-zinc-400 font-semibold uppercase text-[10px] tracking-wider">
                  <th className="py-2 px-2">Model</th>
                  <th className="py-2 px-2">Rates (In/Out 1M)</th>
                  <th className="py-2 px-2 text-right">Cost / Call</th>
                  <th className="py-2 px-2 text-right">Monthly Spend</th>
                  <th className="py-2 px-2 text-right">Price Diff</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-200/60 dark:divide-zinc-800/60">
                {result.comparisons.map((c) => {
                  const isSelected = c.modelId === modelId;
                  return (
                    <tr
                      key={c.modelId}
                      className={`transition-colors ${
                        isSelected
                          ? "bg-teal-50/80 dark:bg-teal-950/40 font-bold"
                          : "hover:bg-zinc-100/50 dark:hover:bg-zinc-900/50"
                      }`}
                    >
                      <td className="py-2.5 px-2 font-medium">
                        <div className="flex items-center gap-1.5">
                          <span className="text-zinc-900 dark:text-white font-bold">{c.modelName}</span>
                          <span className="text-[10px] text-zinc-400 font-normal">({c.provider})</span>
                          {isSelected && (
                            <span className="px-1.5 py-0.5 text-[9px] font-bold rounded bg-teal-600 text-white">
                              Active
                            </span>
                          )}
                        </div>
                      </td>
                      <td className="py-2.5 px-2 font-mono text-[11px] text-zinc-500">
                        ${c.inputCostPerM} / ${c.outputCostPerM}
                      </td>
                      <td className="py-2.5 px-2 text-right font-mono font-bold text-zinc-900 dark:text-zinc-100">
                        {formatCurrencyDetailed(c.costPerRequest)}
                      </td>
                      <td className="py-2.5 px-2 text-right font-mono text-zinc-900 dark:text-zinc-100">
                        {formatCurrencyStandard(c.monthlyCost)}
                      </td>
                      <td className="py-2.5 px-2 text-right font-mono font-bold">
                        {c.savingsVsBaselinePercent === 0 ? (
                          <span className="text-zinc-400">—</span>
                        ) : c.savingsVsBaselinePercent! > 0 ? (
                          <span className="text-emerald-600 dark:text-emerald-400">
                            -{Math.abs(Math.round(c.savingsVsBaselinePercent!))}%
                          </span>
                        ) : (
                          <span className="text-rose-600 dark:text-rose-400">
                            +{Math.abs(Math.round(c.savingsVsBaselinePercent!))}%
                          </span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* ACTION BUTTONS */}
        <div className="flex flex-wrap items-center justify-between gap-2.5 pt-2 border-t border-zinc-200 dark:border-zinc-800">
          <button
            type="button"
            onClick={handleCopy}
            className="flex items-center gap-2 text-xs font-semibold text-zinc-700 dark:text-zinc-300 hover:text-teal-600 dark:hover:text-teal-400 transition-all duration-200 hover:scale-[1.02] bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 px-3.5 py-2 rounded-xl shadow-xs focus:ring-1 focus:ring-teal-500 focus:outline-none"
          >
            {copied ? "✅ Copied Summary!" : "📋 Copy Summary"}
          </button>

          <div className="flex flex-wrap items-center gap-2">
            <ShareResultButton onClick={() => setIsShareModalOpen(true)} />
            <button
              type="button"
              onClick={handleExportTxt}
              className="flex items-center gap-2 text-xs font-semibold text-teal-600 dark:text-teal-400 hover:text-teal-700 dark:hover:text-teal-300 transition-all duration-200 hover:scale-[1.02] bg-teal-50 dark:bg-teal-950/30 px-3.5 py-2 rounded-xl shadow-xs border border-teal-200/50 dark:border-teal-800/50 focus:ring-1 focus:ring-teal-500 focus:outline-none"
            >
              📥 Export TXT
            </button>
            <DownloadPdfButton onClick={handleDownloadPdf} isGenerating={isPdfLoading} />
          </div>
        </div>

        {/* EXPLANATION ACCORDION */}
        <ExplainResultAccordion steps={explanationSteps} />

        {/* DATED PRICING FOOTNOTE (REQUIREMENT 5) */}
        <div className="p-3.5 bg-zinc-100/70 dark:bg-zinc-950/40 border border-zinc-200 dark:border-zinc-800 rounded-xl text-xs text-zinc-500 dark:text-zinc-400 flex items-start gap-2.5">
          <Info size={16} className="text-teal-600 dark:text-teal-400 shrink-0 mt-0.5" />
          <div className="leading-relaxed text-[11px]">
            <strong className="text-zinc-800 dark:text-zinc-200 block mb-0.5 font-bold">
              Pricing Reference Note (Last checked: August 2026)
            </strong>
            Token rates displayed above are approximate estimates based on publicly published provider API documentation. Model pricing updates frequently; please verify current official pricing with OpenAI, Anthropic, Google, or DeepSeek before finalizing commercial budgets.
          </div>
        </div>

      </div>

      {/* SHARE RESULT MODAL */}
      <ShareResultModal
        isOpen={isShareModalOpen}
        onClose={() => setIsShareModalOpen(false)}
        data={{
          toolName: "AI Token Cost Calculator",
          toolSlug: "ai-token-cost-calculator",
          category: "Utilities & Dev",
          resultValue: formatCurrencyDetailed(result.costPerRequest),
          resultLabel: `Cost per API call (${result.selectedModel.name})`,
          inputsSummary: [
            { label: "Model", value: result.selectedModel.name },
            { label: "Input Tokens", value: result.inputTokens.toLocaleString() },
            { label: "Output Tokens", value: result.outputTokens.toLocaleString() },
            { label: "Monthly Volume", value: `${formatCurrencyStandard(result.monthlyTotalCost)} (${result.requestsPerMonth.toLocaleString()} calls)` },
          ],
          queryParams: {
            m: modelId,
            in: effectiveInputTokens.toString(),
            out: effectiveOutputTokens.toString(),
            req: requestsPerDay.toString(),
          },
        }}
      />
    </div>
  );
}
