export interface ToolMethodology {
  slug: string;
  toolName: string;
  category: "Health & Fitness" | "Finance & Math" | "Utilities & Programming";
  standardName: string;
  formulaText?: string;
  summary: string;
  detailedParagraph: string;
}

export const methodologyData: ToolMethodology[] = [
  {
    slug: "bmi-calculator",
    toolName: "BMI Calculator",
    category: "Health & Fitness",
    standardName: "World Health Organization (WHO) Body Mass Index Classification",
    formulaText: "BMI = Weight (kg) / [Height (m)]²  OR  BMI = [Weight (lbs) / [Height (in)]²] × 703",
    summary: "Uses Quetelet's ratio mapped to WHO clinical weight bands (<18.5 Underweight, 18.5–24.9 Normal, 25–29.9 Overweight, ≥30 Obese).",
    detailedParagraph: "We compute Body Mass Index (BMI) using the standard Quetelet ratio and map results directly to World Health Organization (WHO) clinical weight bands: Underweight (<18.5), Normal weight (18.5–24.9), Overweight (25–29.9), and Obese (≥30). Because BMI measures gross physical proportion rather than lean muscle mass versus adipose tissue, we provide explicit clinical interpretation caveats alongside every result.",
  },
  {
    slug: "calorie-calculator",
    toolName: "Calorie & TDEE Calculator",
    category: "Health & Fitness",
    standardName: "Mifflin-St Jeor Equation & FAO/WHO Activity Multipliers",
    formulaText: "BMR (Men) = 10W + 6.25H - 5A + 5 | BMR (Women) = 10W + 6.25H - 5A - 161",
    summary: "Estimates Basal Metabolic Rate (BMR) using Mifflin-St Jeor and applies Physical Activity Level (PAL) multipliers (1.2 to 1.9).",
    detailedParagraph: "We calculate Basal Metabolic Rate (BMR) using the Mifflin-St Jeor equation, proven in clinical trials to estimate baseline caloric expenditure within ±10% for modern adults. Total Daily Energy Expenditure (TDEE) is calculated by multiplying BMR by physical activity level (PAL) coefficients ranging from 1.2 (sedentary) to 1.9 (intense daily training).",
  },
  {
    slug: "macro-calculator",
    toolName: "Macro Calculator",
    category: "Health & Fitness",
    standardName: "Atwater Energy Coefficients & Macronutrient Gram Distribution Model",
    formulaText: "Protein (g) = (kcal × P%) / 4 | Carbs (g) = (kcal × C%) / 4 | Fat (g) = (kcal × F%) / 9",
    summary: "Converts Total Daily Energy Expenditure (TDEE) and goal caloric targets into daily macronutrient gram requirements (protein, carbs, fat).",
    detailedParagraph: "Macronutrient calculations convert daily target calories into specific gram targets using standard Atwater energy coefficients: 4 calories per gram for protein and carbohydrates, and 9 calories per gram for dietary fat. Target calories are derived from Mifflin-St Jeor TDEE math adjusted for fitness goal deficits (-500 kcal for fat loss) or surpluses (+500 kcal for muscle gain).",
  },
  {
    slug: "water-intake-calculator",
    toolName: "Water Intake Calculator",
    category: "Health & Fitness",
    standardName: "European Food Safety Authority (EFSA) Hydration Guidelines",
    formulaText: "Daily Water (L) = (Weight in kg × 0.035) + (Exercise Minutes / 30 × 0.35L)",
    summary: "Calculates baseline fluid needs based on body mass (35ml/kg) adjusted for physical activity duration and climate exposure.",
    detailedParagraph: "Our hydration model follows European Food Safety Authority (EFSA) baseline recommendations, establishing a foundational intake of ~35ml of fluid per kilogram of body weight. The formula dynamically scales upward based on physical activity duration to compensate for sweat loss.",
  },
  {
    slug: "sleep-cycle-calculator",
    toolName: "Sleep Cycle Calculator",
    category: "Health & Fitness",
    standardName: "Ultradian 90-Minute Sleep Architecture Cycle Model",
    formulaText: "Target Wake Time = Bedtime + (N × 90 min) + 15 min latency",
    summary: "Calculates optimal bedtimes and wake times in 90-minute ultradian cycles accounting for a 15-minute average sleep onset latency.",
    detailedParagraph: "Calculations rely on standard sleep medicine ultradian rhythm research, which demonstrates that healthy human sleep progresses through distinct NREM and REM stages lasting approximately 90 minutes. We add an average 15-minute sleep onset latency buffer so you wake up feeling refreshed at the natural end of a cycle.",
  },
  {
    slug: "due-date-calculator",
    toolName: "Pregnancy Due Date Calculator",
    category: "Health & Fitness",
    standardName: "Naegele's Rule & 280-Day Gestational Age Standard",
    formulaText: "EDD = Last Menstrual Period (LMP) + 1 year - 3 months + 7 days",
    summary: "Estimates delivery date using Naegele's Rule assuming a standard 280-day (40-week) gestation period from last menstrual period.",
    detailedParagraph: "Estimated Date of Delivery (EDD) is calculated using Naegele’s Rule, the gold standard in clinical obstetrics. The formula adds 280 days (40 weeks) to the first day of the last menstrual period (LMP) assuming a standard 28-day menstrual cycle, providing trimester milestones and gestational progress.",
  },
  {
    slug: "gfr-kidney-function-calculator",
    toolName: "GFR / Kidney Function Calculator",
    category: "Health & Fitness",
    standardName: "2021 CKD-EPI Creatinine Equation (Race-Free NKF/ASN Standard)",
    formulaText: "eGFR = 142 × min(Scr/κ, 1)^α × max(Scr/κ, 1)^-1.200 × 0.9938^Age × [1.012 if Female]",
    summary: "Estimates Glomerular Filtration Rate (eGFR in mL/min/1.73m²) and classifies Chronic Kidney Disease (CKD) stages 1 through 5.",
    detailedParagraph: "Our renal estimation algorithm strictly implements the 2021 race-free CKD-EPI creatinine equation recommended by the National Kidney Foundation (NKF) and American Society of Nephrology (ASN). The model refactors biological sex, age, and serum creatinine parameters to evaluate kidney filtration capacity and map results to official KDIGO Chronic Kidney Disease stage categories.",
  },
  {
    slug: "intermittent-fasting-calculator",
    toolName: "Intermittent Fasting Calculator",
    category: "Health & Fitness",
    standardName: "Circadian Rhythm & Fasting-State Time Partitioning Model",
    formulaText: "Fasting Window = 24 - Eating Window (Hours) | Live Countdown = Target Phase Time - Current Time",
    summary: "Calculates precise daily fasting and eating window boundaries with real-time ticking phase countdown timers.",
    detailedParagraph: "Our intermittent fasting engine computes exact time boundaries for popular schedules (16:8, 18:6, 20:4, OMAD) based on user-designated meal anchor times. It evaluates current local device time every second to calculate phase transitions, progress percentages, and real-time remaining countdowns.",
  },
  {
    slug: "pregnancy-weight-gain-calculator",
    toolName: "Pregnancy Weight Gain Calculator",
    category: "Health & Fitness",
    standardName: "Institute of Medicine (IOM) & ACOG Trimester Growth Charts",
    formulaText: "Gain Target = Pre-pregnancy BMI Baseline + Trimester Weight Rate (0.5–1.0 lb/wk)",
    summary: "Tracks weight gain targets against Institute of Medicine (IOM) clinical guidelines based on pre-pregnancy BMI category.",
    detailedParagraph: "Recommended pregnancy weight targets follow the U.S. Institute of Medicine (IOM) and American College of Obstetricians and Gynecologists (ACOG) guidelines. Recommended total weight gain varies based on pre-pregnancy BMI category, scaling from 28–40 lbs for underweight baselines down to 11–20 lbs for obese baselines.",
  },
  {
    slug: "loan-calculator",
    toolName: "Loan & EMI Calculator",
    category: "Finance & Math",
    standardName: "Standard Reducing-Balance Compound Amortization Equation",
    formulaText: "EMI = P × [r(1+r)ⁿ] / [(1+r)ⁿ - 1]",
    summary: "Computes Equal Monthly Installments (EMI) using reducing-balance compound interest and generates full principal/interest schedules.",
    detailedParagraph: "Loan payments are computed using standard reducing-balance compound amortization formulas used by commercial banks. Monthly interest is recalculated on the remaining principal balance after each payment, delivering exact interest breakdowns over the loan tenure.",
  },
  {
    slug: "salary-take-home-calculator",
    toolName: "Salary Take-Home Pay Calculator",
    category: "Finance & Math",
    standardName: "US Progressive Federal Tax Brackets & FICA Statutory Rates",
    formulaText: "Net Pay = Gross Pay - (Federal Income Tax + State Tax + 6.2% Social Security + 1.45% Medicare)",
    summary: "Applies progressive marginal tax brackets, standard deduction offsets, and mandatory FICA payroll tax rates.",
    detailedParagraph: "Paycheck estimations use progressive tax bracket calculations matching federal IRS tax code logic. Gross income is adjusted for the standard deduction, and marginal rates are applied sequentially alongside FICA payroll withholdings (6.2% Social Security up to wage caps, 1.45% Medicare).",
  },
  {
    slug: "currency-converter",
    toolName: "Live Currency Converter",
    category: "Finance & Math",
    standardName: "Mid-Market Real-Time Foreign Exchange Rates (ECB Standard)",
    formulaText: "Converted Amount = Amount × Target Rate / Source Rate",
    summary: "Converts fiat currencies using real-time mid-market exchange rates without markup or hidden spreads.",
    detailedParagraph: "Currencies are converted using live mid-market exchange rates derived from European Central Bank (ECB) and institutional forex data feeds. Calculations evaluate exact cross-currency rates without retail spreads or bank markups.",
  },
  {
    slug: "budget-calculator",
    toolName: "50/30/20 Budget Calculator",
    category: "Finance & Math",
    standardName: "Elizabeth Warren 50/30/20 Balanced Proportional Rule",
    formulaText: "Needs = Income × 0.50 | Wants = Income × 0.30 | Savings = Income × 0.20",
    summary: "Splits net monthly income into 50% essential needs, 30% discretionary wants, and 20% savings & debt reduction.",
    detailedParagraph: "Budgets are generated according to the 50/30/20 financial planning rule popularized by Senator Elizabeth Warren. Net take-home income is allocated into 50% essential needs (housing, utilities, food), 30% discretionary wants, and 20% savings and high-interest debt repayment.",
  },
  {
    slug: "freelance-rate-calculator",
    toolName: "Freelance Rate Calculator",
    category: "Finance & Math",
    standardName: "Billable Utilization & Overhead Revenue Cost Model",
    formulaText: "Minimum Rate = (Desired Net Income + Annual Expenses) / (Work Weeks × Weekly Hours × Billable %)",
    summary: "Calculates baseline billable hourly and daily rates to cover target net income, operating expenses, taxes, and non-billable overhead hours.",
    detailedParagraph: "Freelance hourly rate calculations divide total required gross annual revenue (desired personal net income plus annual business operating expenses) by total annual billable hours. Billable hours account for annual active work weeks (excluding vacation and holidays) and the billable time ratio (typically 70%), ensuring that unbilled administrative, marketing, and sales hours are fully subsidized by billable client work.",
  },
  {
    slug: "savings-growth-calculator",
    toolName: "Savings Growth Calculator",
    category: "Finance & Math",
    standardName: "Compound Interest Formula with Periodic Deposits",
    formulaText: "A = P(1 + r/n)ⁿᵗ + PMT × [(1 + r/n)ⁿᵗ - 1] / (r/n)",
    summary: "Models compound investment growth with initial principal, recurring deposits, and compounding frequencies.",
    detailedParagraph: "Growth projections utilize the standard compound interest formula for annuity investments. The calculation evaluates future value ($A$) by compounding both the initial principal ($P$) and recurring monthly/annual deposits ($PMT$) across specified annual return rates.",
  },
  {
    slug: "retirement-calculator",
    toolName: "Retirement Savings Calculator",
    category: "Finance & Math",
    standardName: "Bengen 4% Rule & Future Value Annuity Accumulation",
    formulaText: "Required Corpus = Desired Annual Expense / 0.04",
    summary: "Projects required nest egg using the Bengen 4% Safe Withdrawal Rule combined with inflation-adjusted compound accumulation.",
    detailedParagraph: "Retirement sufficiency is evaluated using William Bengen’s 4% Safe Withdrawal Rate rule alongside compound growth math. The calculator projects inflation-adjusted annual living expenses in retirement and determines the target portfolio corpus required to sustain withdrawals.",
  },
  {
    slug: "inflation-calculator",
    toolName: "Inflation Calculator",
    category: "Finance & Math",
    standardName: "US Bureau of Labor Statistics Consumer Price Index (CPI-U)",
    formulaText: "Future Value = Present Value × (1 + Inflation Rate)ⁿ",
    summary: "Calculates purchasing power erosion over time using historical or projected Consumer Price Index (CPI) percentages.",
    detailedParagraph: "Purchasing power calculations apply the Consumer Price Index (CPI) compound adjustment formula. The tool determines how historical inflation degrades real purchasing power or calculates the future nominal amount required to match today's buying power.",
  },
  {
    slug: "discount-calculator",
    toolName: "Discount & Sale Calculator",
    category: "Finance & Math",
    standardName: "Multi-Tier Percentage Markdown & Net Sales Tax Math",
    formulaText: "Final Price = [Original × (1 - d₁) × (1 - d₂)] × (1 + Tax Rate)",
    summary: "Calculates total savings, stacked percentage discounts, and final out-of-pocket price including local sales tax.",
    detailedParagraph: "Sale prices are calculated by applying primary and stacked secondary percentage markdowns sequentially to the original sticker price. Regional sales tax is applied to the net discounted subtotal to give the exact out-of-pocket total.",
  },
  {
    slug: "group-expense-splitter",
    toolName: "Group Expense Splitter",
    category: "Finance & Math",
    standardName: "Greedy Debt-Simplification Graph Minimization Algorithm",
    formulaText: "Net Balance = Total Paid - Equal Share",
    summary: "Calculates net individual balances and minimizes the total number of reimbursement transactions required.",
    detailedParagraph: "Group balances are resolved using a greedy graph minimization algorithm. After computing each participant's net positive or negative balance relative to the average share, the algorithm pairs maximum debtors with maximum creditors to settle all group debts in the fewest transfers.",
  },
  {
    slug: "habit-cost-calculator",
    toolName: "Habit Cost Calculator",
    category: "Finance & Math",
    standardName: "Compound Opportunity Cost & Future Investment Value",
    formulaText: "Opportunity Cost = FV(Daily Habit Expense, Market Return Rate, Years)",
    summary: "Quantifies cumulative spending on daily habits (coffee, smoking, subscriptions) and projects 10–30 year investment opportunity cost.",
    detailedParagraph: "Habit costs are calculated by compounding daily expenditure across monthly, annual, and multi-decade time horizons. We then calculate investment opportunity cost by projecting what those funds would grow to if invested in an index fund earning a standard 7–8% annual compound return.",
  },
  {
    slug: "tip-calculator",
    toolName: "Tip & Bill Splitter",
    category: "Finance & Math",
    standardName: "Standard Percentage Gratuity & Symmetric Partitioning",
    formulaText: "Total Bill = Subtotal × (1 + Tip % / 100) | Per Person = Total Bill / Headcount",
    summary: "Calculates custom gratuity percentages and divides totals evenly across dining guests with per-person breakdowns.",
    detailedParagraph: "Gratuity is calculated by multiplying the pre-tax or post-tax bill subtotal by the selected tip percentage. The sum of the subtotal and total tip is divided evenly across all dining guests to calculate exact per-person obligations rounded to the nearest cent.",
  },
  {
    slug: "zakat-calculator",
    toolName: "Zakat Calculator",
    category: "Finance & Math",
    standardName: "Classical Fiqh Nisab Thresholds (87.48g Gold / 612.36g Silver) & 2.5% Lunar Rate",
    formulaText: "Payable Zakat = (Net Eligible Assets - Short-term Debts) × 0.025",
    summary: "Calculates 2.5% Zakat on net eligible wealth above Nisab thresholds (87.48g gold / 612.36g silver) over one lunar year.",
    detailedParagraph: "Zakat calculations follow established Islamic jurisprudential standards. The Nisab minimum threshold is determined using current market values for 87.48 grams of pure 24k gold (7.5 Tolas) or 612.36 grams of pure silver (52.5 Tolas). Zakat is levied at 2.5% on net zakat-eligible liquid assets held for one lunar year.",
  },
  {
    slug: "age-calculator",
    toolName: "Age Calculator",
    category: "Utilities & Programming",
    standardName: "Gregorian Calendar Chronological Duration Standard",
    formulaText: "Exact Age = Target Date - Birth Date (in Years, Months, Days)",
    summary: "Calculates exact chronological age in years, months, days, total hours, and minutes accounting for leap years.",
    detailedParagraph: "Chronological age is calculated by computing the exact delta between birth date and target date in UTC time. The algorithm accounts for variable month lengths (28 to 31 days) and leap years (February 29th insertions) to return precise breakdowns.",
  },
  {
    slug: "ai-token-cost-calculator",
    toolName: "AI Token Cost Calculator",
    category: "Utilities & Programming",
    standardName: "Byte-Pair Encoding (BPE) & Autoregressive Inference Cost Model",
    formulaText: "Total Cost = (Input Tokens / 1M × Input Rate) + (Output Tokens / 1M × Output Rate)",
    summary: "Calculates LLM API call costs and projected monthly volume budgets across top AI models (GPT-4o, Claude 3.5, Gemini 1.5, DeepSeek).",
    detailedParagraph: "Our token cost model applies provider-specific per-million-token input and output rates against user prompt volumes. For text inputs, it applies the standard ~0.75 words-per-token ratio to approximate token usage, projecting daily, monthly, and annual API budgets with real-time side-by-side model comparison.",
  },
  {
    slug: "gpa-converter",
    toolName: "GPA Converter",
    category: "Utilities & Programming",
    standardName: "Standard 4.0 US Unweighted / 5.0 Weighted Grading Scale",
    formulaText: "GPA = Σ(Grade Points × Course Credits) / Total Credits",
    summary: "Converts letter grades, percentages, or international scores into standard 4.0 unweighted or weighted GPA scales.",
    detailedParagraph: "Grade Point Averages are calculated by converting letter grades to numeric quality points (A=4.0, B=3.0, C=2.0, D=1.0, F=0) weighted by course credit hours. Weighted GPAs add 0.5 to 1.0 bonus points for Honors, IB, or AP coursework.",
  },
  {
    slug: "password-generator",
    toolName: "Password Generator",
    category: "Utilities & Programming",
    standardName: "NIST SP 800-63B Guidelines & CSPRNG Shannon Entropy",
    formulaText: "Entropy (bits) = Password Length × log₂(Character Pool Size)",
    summary: "Generates high-entropy random passwords using the browser Web Crypto API (window.crypto.getRandomValues).",
    detailedParagraph: "Passwords are generated using the browser's native Cryptographically Secure Pseudorandom Number Generator (`window.crypto.getRandomValues`). Theoretical security strength is evaluated in bits of Shannon entropy based on password character length and pool complexity.",
  },
  {
    slug: "word-character-counter",
    toolName: "Word & Character Counter",
    category: "Utilities & Programming",
    standardName: "Unicode Grapheme Cluster & Text Metrics Specification",
    formulaText: "Word Count = RegEx Match (\\S+) | Reading Time = Words / 200 WPM",
    summary: "Analyzes text length, character count with/without spaces, paragraph count, and estimated reading/speaking time.",
    detailedParagraph: "Text metrics are processed client-side using regex tokenization and Unicode grapheme cluster counting. Reading time is estimated using the standard silent reading rate of 200 words per minute (WPM), while speaking time assumes 130 WPM.",
  },
  {
    slug: "pace-calculator",
    toolName: "Running Pace Calculator",
    category: "Utilities & Programming",
    standardName: "Kinematic Speed & Distance Time Velocity Metric",
    formulaText: "Pace = Total Time / Distance | Projected Time = Distance × Average Pace",
    summary: "Calculates running pace per mile or kilometer and projects finish times for standard race distances (5K, 10K, Marathon).",
    detailedParagraph: "Pace calculations divide elapsed completion time by total distance covered. Race projections apply Riegel’s formula ($T_2 = T_1 \times (D_2 / D_1)^{1.06}$) to estimate fatigue curves across longer distances.",
  },
  {
    slug: "timezone-meeting-planner",
    toolName: "Timezone Meeting Planner",
    category: "Utilities & Programming",
    standardName: "IANA Time Zone Database (TZDB) & UTC Offset Standard",
    formulaText: "Local Time = UTC + Destination Offset (Adjusted for DST)",
    summary: "Converts times across international zones using IANA database rules including Daylight Saving Time transitions.",
    detailedParagraph: "Time conversions utilize the official IANA Time Zone Database (TZDB) maintained by ICANN. Calculations resolve exact UTC offsets for multiple geographic regions while handling Daylight Saving Time (DST) transitions.",
  },
  {
    slug: "percentage-calculator",
    toolName: "Percentage Calculator",
    category: "Utilities & Programming",
    standardName: "Classical Algebraic Proportion & Relative Change Formula",
    formulaText: "% Change = [(Value₂ - Value₁) / Value₁] × 100 | Part = Whole × (Percent / 100)",
    summary: "Solves percentage increase/decrease, relative differences, and proportion equations instantly.",
    detailedParagraph: "Calculations execute standard algebraic percentage equations: evaluating what percent $A$ is of $B$, finding value after percentage change ($\Delta\% = \frac{V_2 - V_1}{V_1} \times 100$), and calculating part-to-whole proportions.",
  },
  {
    slug: "speech-time-calculator",
    toolName: "Words-to-Minutes / Speech Time Calculator",
    category: "Utilities & Programming",
    standardName: "Public Speaking Words-Per-Minute Pacing Model & Lexical Tokenization",
    formulaText: "Duration (min) = Words ÷ WPM | Target Words = Duration (min) × WPM",
    summary: "Estimates spoken presentation duration from script word count or calculates target word counts across Slow (110 WPM), Average (140 WPM), and Fast (170 WPM) pacing presets.",
    detailedParagraph: "Our speech duration engine uses regex-based whitespace tokenization to count script words and maps them against established public speaking pace benchmarks: Slow Keynote (110 WPM), Average Presentation (140 WPM), and Fast Conversational (170 WPM). Reverse mode calculates target script word counts for strict presentation time limits.",
  },
  {
    slug: "ats-resume-checker",
    toolName: "ATS Resume Score Checker",
    category: "Utilities & Programming",
    standardName: "Browser-Local Lexical Stemming & Term Frequency Keyword Extraction Model",
    formulaText: "Match Score (%) = [Matched Target Keywords ÷ Total Target Keywords] × 100",
    summary: "Parses resume text against target job descriptions to extract key skills, compute match percentages, identify missing terms, and audit ATS layout structure 100% privately in browser memory.",
    detailedParagraph: "Our ATS resume engine tokenizes job description text, strips common English stop-words, and ranks domain terms by frequency. It performs suffix stemming (e.g. 'manage/managing/managed') to match candidate experience against position requirements while auditing essential section headers and formatting constraints.",
  },
  {
    slug: "work-hours-calculator",
    toolName: "Work Hours / Timesheet Calculator",
    category: "Finance & Math",
    standardName: "FLSA Weekly Hour Summation & Overtime Math Model",
    formulaText: "Net Shift Hours = (End Time - Start Time) - Break Mins | Overtime Pay = OT Hours × (Rate × 1.5)",
    summary: "Calculates total shift hours, unpaid break deductions, overnight shift spans across midnight, and gross earnings with 1.5x overtime threshold rules.",
    detailedParagraph: "Our timesheet calculation engine converts clock-in and clock-out time strings into minutes from midnight, applying 24-hour (+1440 mins) modulo adjustments for overnight shifts. It subtracts unpaid break durations and applies 1.5x overtime multipliers for hours exceeding weekly thresholds.",
  },
  {
    slug: "retirement-withdrawal-simulator",
    toolName: "Retirement Safe Withdrawal Rate Simulator",
    category: "Finance & Math",
    standardName: "Bengen 4% Rule & Trinity Study Historical Backtesting Model",
    formulaText: "Annual Withdrawal_t = Annual Withdrawal_{t-1} × (1 + CPI_t) | Portfolio Growth = Balance × (1 + R_weighted)",
    summary: "Backtests retirement withdrawal sustainability across 96 years of US historical stock, bond, and CPI market data (1928-2023) to compute sequence survival probability.",
    detailedParagraph: "Our retirement safe withdrawal rate engine evaluates rolling N-year distribution sequences starting from every possible year in our 96-year US market dataset. It applies user-defined stock/bond allocation weighting (S&P 500 total return vs 10-Year Treasury bonds) and annual CPI inflation adjustments to test portfolio longevity and sequence-of-returns risk.",
  },
  {
    slug: "readability-score-calculator",
    toolName: "Readability Score Calculator",
    category: "Utilities & Programming",
    standardName: "Flesch Reading Ease, Flesch-Kincaid Grade Level & Gunning Fog Index",
    formulaText: "Flesch Ease = 206.835 - 1.015(W/S) - 84.6(Syl/W) | Kincaid Grade = 0.39(W/S) + 11.8(Syl/W) - 15.59",
    summary: "Audits text readability in real-time across Flesch Reading Ease, Flesch-Kincaid Grade Level, and Gunning Fog Index using English syllable counting algorithms.",
    detailedParagraph: "Our readability engine parses text into sentences, words, and syllables. It evaluates Flesch Reading Ease (0-100 scale), Flesch-Kincaid Grade Level (US school grades), and Gunning Fog Index (years of formal education needed) while providing detailed lexical statistics.",
  },
  {
    slug: "internet-speed-test",
    toolName: "Internet Speed Test",
    category: "Utilities & Programming",
    standardName: "Streaming HTTP Chunk Bandwidth & Latency Sampling Model",
    formulaText: "Mbps = (Bytes × 8) / (1,000,000 × Seconds) | Jitter = Mean(|Ping_{i+1} - Ping_i|)",
    summary: "Measures real-time download Mbps, upload Mbps, ping latency, and jitter using streaming HTTP binary chunk payloads with TCP slow-start window filtering.",
    detailedParagraph: "Our internet speed test engine streams uncompressible binary chunks between the browser and our server API endpoints over 4.5-second sampling windows. It discards initial 300ms TCP slow-start warmup intervals to calculate uncompressed throughput, ping latency, and jitter.",
  },
  {
    slug: "qr-code-generator",
    toolName: "QR Code Generator",
    category: "Utilities & Programming",
    standardName: "ISO/IEC 18004 QR Code Matrix & Reed-Solomon Error Correction Model",
    formulaText: "Error Correction Capability: L (~7%), M (~15%), Q (~25%), H (~30%)",
    summary: "Encodes website URLs, WiFi network credentials, and vCard contact cards into two-dimensional matrix QR codes with custom color palettes and high-resolution PNG/SVG vector exports.",
    detailedParagraph: "Our QR code generation engine formats structured payload strings (URL, WiFi, vCard 3.0) and renders matrix modules using Reed-Solomon error correction algorithms. It supports custom foreground/background colors and automatic High Error Correction (H - 30%) when embedding center logo overlays.",
  },
  {
    slug: "digital-storage-converter",
    toolName: "Digital Storage Converter",
    category: "Utilities & Programming",
    standardName: "SI Decimal (1000-based) & IEC 60027-2 Binary (1024-based) Standards",
    formulaText: "Bytes = Value × Base^Power (Base = 1000 for SI, 1024 for IEC)",
    summary: "Converts digital data quantities across 7 storage units simultaneously using both 1000-based decimal and 1024-based binary standards.",
    detailedParagraph: "Our digital storage conversion engine implements both International System of Units (SI 1000-based) decimal standards (KB, MB, GB, TB) and International Electrotechnical Commission (IEC 1024-based) binary standards (KiB, MiB, GiB, TiB). It calculates simultaneous equivalents across bits, bytes, and multi-gigabyte units while clarifying operating system disk formatting reporting differences.",
  },
  {
    slug: "json-csv-converter",
    toolName: "JSON to CSV Converter",
    category: "Utilities & Programming",
    standardName: "RFC 4180 CSV Standard & Nested Array Flattening",
    formulaText: "Delimited Output = Field Escaping + Header Union + Row Serialization",
    summary: "Parses, flattens, and serializes JSON objects into RFC 4180 compliant CSV tables entirely in-browser.",
    detailedParagraph: "Data conversion follows the RFC 4180 CSV specification. Nested JSON structures are flattened into key-value paths, and strings containing commas, quotes, or line breaks are properly escaped without sending data to an external server.",
  },
  {
    slug: "regex-tester",
    toolName: "Regex Tester",
    category: "Utilities & Programming",
    standardName: "ECMAScript (JavaScript) Regular Expression Engine",
    formulaText: "Matches = Pattern.exec(String) with /g, /i, /m, /u flags",
    summary: "Tests JavaScript regular expressions in real-time with syntax highlighting, capture groups, and replacement tools.",
    detailedParagraph: "Regex evaluation is powered directly by your browser’s native ECMAScript RegExp engine. Test strings are evaluated against pattern flags (`g`, `i`, `m`, `s`, `u`, `y`), highlighting match groups and replacement strings with zero latency.",
  },
  {
    slug: "color-palette-generator",
    toolName: "Color Palette Generator",
    category: "Utilities & Programming",
    standardName: "HSL/HSV Color Space Harmonic Angles & WCAG 2.1 Contrast",
    formulaText: "Complementary = Hue + 180° | Triadic = Hue ± 120° | Contrast = (L1 + 0.05) / (L2 + 0.05)",
    summary: "Generates color palettes using HSL color harmonics and measures WCAG 2.1 accessibility contrast ratios.",
    detailedParagraph: "Palettes are calculated in the HSL (Hue, Saturation, Lightness) color space by applying geometric angle offsets across the 360° color wheel. Text contrast against background colors is calculated using the WCAG 2.1 relative luminance equation.",
  },
  {
    slug: "shoe-size-converter",
    toolName: "Shoe Size Converter",
    category: "Utilities & Programming",
    standardName: "ISO/TS 19407 Footwear Sizing & Brannock Barleycorn System",
    formulaText: "US Size = (Foot Length in inches × 3) - 22 | EU Size = (Foot Length in cm + 1.5) × 1.5",
    summary: "Converts shoe measurements between US, UK, EU, JP, and CM sizing standards for men, women, and kids.",
    detailedParagraph: "Sizing conversions implement ISO/TS 19407 international footwear standards and the traditional Brannock barleycorn system (1/3 inch increments). Conversions map physical foot length in centimeters to regional sizing scales.",
  },
  {
    slug: "paper-fabric-size-converter",
    toolName: "Paper & Fabric Size Converter",
    category: "Utilities & Programming",
    standardName: "ISO 216 Paper Standard (1:√2 Ratio) & Fabric Weight (GSM vs OZ/YD²)",
    formulaText: "GSM = OZ/YD² × 33.906 | A(n) Dimensions = 1000/√2ⁿ × 1000/√2ⁿ⁺¹ mm",
    summary: "Converts ISO 216 paper dimensions (A0–A8, B0–B8) and fabric weight densities (GSM to oz/yd²).",
    detailedParagraph: "Paper calculations use the ISO 216 international standard based on the $1:\sqrt{2}$ aspect ratio, where each size is created by folding the prior size in half. Fabric conversions use the density factor $1 \text{ oz/yd}^2 = 33.906 \text{ g/m}^2$.",
  },
  {
    slug: "travel-time-fuel-calculator",
    toolName: "Travel Time & Fuel Calculator",
    category: "Utilities & Programming",
    standardName: "Physical Kinematics & Volumetric Consumption Rate",
    formulaText: "Fuel Needed = Distance / MPG | Total Cost = Fuel Needed × Price per Gallon",
    summary: "Estimates driving duration, total fuel volume needed, and trip cost based on MPG and fuel price.",
    detailedParagraph: "Trip durations are calculated by dividing route distance by average travel speed. Required fuel volume is determined by dividing total distance by vehicle fuel efficiency (MPG or L/100km) and multiplying by current local fuel prices.",
  },
  {
    slug: "etsy-fee-calculator",
    toolName: "Etsy Fee & Net Profit Calculator",
    category: "Finance & Math",
    standardName: "Etsy 2026 Seller Fee Policy & Multi-Tier Payment Processing Structure",
    formulaText: "Net Profit = (Price + Shipping) - [Listing ($0.20) + 6.5% Transaction + (Processing% × Total + Fixed) + Regulatory% + Ads% + COGS + Actual Shipping]",
    summary: "Calculates itemized Etsy seller commissions, 6.5% transaction cut, country payment processing slabs, regulatory fees, and breakeven pricing.",
    detailedParagraph: "Fee computations adhere to Etsy's official 2026 seller policy schedule. Transaction commissions (6.5%) and payment processing fees apply to gross customer payments including item price and shipping collected. Breakeven item prices are calculated algebraically by solving for the exact listing price where gross margin minus total variable and fixed deductions equals zero.",
  },
  {
    slug: "solar-payback-calculator",
    toolName: "Solar Panel ROI & Payback Calculator",
    category: "Finance & Math",
    standardName: "NREL PVWatts Solar Performance Derating & Compound Discounted Cash Flow Model",
    formulaText: "Annual Gen = kW × Sun Hours × 365 × 0.85 PR | Payback Year = Net Inv / Compound Annual Savings",
    summary: "Calculates solar panel payback period, 25-year cumulative cash flows, LCOE per kWh, and carbon offset.",
    detailedParagraph: "Solar production modeling utilizes the standard National Renewable Energy Laboratory (NREL) PVWatts performance ratio (0.85 derating factor) accounting for inverter, wiring, dust, and temperature losses. Financial returns simulate a dynamic 25-year cash flow combining compound utility rate inflation with 0.5%/year photovoltaic degradation to calculate precise breakeven payback years and Levelized Cost of Energy (LCOE).",
  },
];

export function getToolMethodology(slug: string): ToolMethodology | undefined {
  return methodologyData.find((m) => m.slug === slug);
}
