export interface StateCalculatorItem {
  name: string;
  slug: string;
  abbrev: string;
  href: string;
  title: string;
  description: string;
  taxType: "flat" | "graduated" | "none";
  topRateText: string;
  hasIncomeTax: boolean;
  isLive: boolean;
  badge?: string;
}

export const STATE_CALCULATORS: StateCalculatorItem[] = [
  {
    name: "Alabama",
    slug: "alabama",
    abbrev: "AL",
    href: "/tools/alabama-salary-calculator",
    title: "Alabama Salary Calculator",
    description: "Calculate Alabama take-home pay after 2.0% to 5.0% graduated state income tax and FICA.",
    taxType: "graduated",
    topRateText: "5.0%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Alaska",
    slug: "alaska",
    abbrev: "AK",
    href: "/tools/alaska-salary-calculator",
    title: "Alaska Salary Calculator",
    description: "Calculate Alaska take-home pay with 0.0% state personal income tax withholding.",
    taxType: "none",
    topRateText: "0.0%",
    hasIncomeTax: false,
    isLive: false,
  },
  {
    name: "Arizona",
    slug: "arizona",
    abbrev: "AZ",
    href: "/tools/arizona-salary-calculator",
    title: "Arizona Salary Calculator",
    description: "Calculate Arizona take-home pay with the statutory 2.5% flat state income tax rate.",
    taxType: "flat",
    topRateText: "2.5%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Arkansas",
    slug: "arkansas",
    abbrev: "AR",
    href: "/tools/arkansas-salary-calculator",
    title: "Arkansas Salary Calculator",
    description: "Calculate Arkansas take-home pay after the updated 3.7% top marginal tax rate, progressive brackets, and FICA.",
    taxType: "graduated",
    topRateText: "3.7%",
    hasIncomeTax: true,
    isLive: true,
    badge: "3.7% Graduated",
  },
  {
    name: "California",
    slug: "california",
    abbrev: "CA",
    href: "/tools/california-salary-calculator",
    title: "California Salary Calculator",
    description: "Calculate California take-home pay across 1.0% to 13.3% progressive state income tax tiers.",
    taxType: "graduated",
    topRateText: "13.3%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Colorado",
    slug: "colorado",
    abbrev: "CO",
    href: "/tools/colorado-salary-calculator",
    title: "Colorado Salary Calculator",
    description: "Calculate Colorado take-home pay with the flat 4.4% state income tax rate.",
    taxType: "flat",
    topRateText: "4.4%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Connecticut",
    slug: "connecticut",
    abbrev: "CT",
    href: "/tools/connecticut-salary-calculator",
    title: "Connecticut Salary Calculator",
    description: "Calculate Connecticut take-home pay after graduated state income tax brackets up to 6.99%.",
    taxType: "graduated",
    topRateText: "6.99%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Delaware",
    slug: "delaware",
    abbrev: "DE",
    href: "/tools/delaware-salary-calculator",
    title: "Delaware Salary Calculator",
    description: "Calculate Delaware take-home pay with graduated brackets from 2.2% to 6.6%.",
    taxType: "graduated",
    topRateText: "6.6%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Florida",
    slug: "florida",
    abbrev: "FL",
    href: "/tools/florida-salary-calculator",
    title: "Florida Salary Calculator",
    description: "Calculate Florida take-home pay with 0.0% state individual wage withholding.",
    taxType: "none",
    topRateText: "0.0%",
    hasIncomeTax: false,
    isLive: false,
  },
  {
    name: "Georgia",
    slug: "georgia",
    abbrev: "GA",
    href: "/tools/georgia-salary-calculator",
    title: "Georgia Salary Calculator",
    description: "Calculate Georgia take-home pay with the flat 5.39% individual state tax rate.",
    taxType: "flat",
    topRateText: "5.39%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Hawaii",
    slug: "hawaii",
    abbrev: "HI",
    href: "/tools/hawaii-salary-calculator",
    title: "Hawaii Salary Calculator",
    description: "Calculate Hawaii take-home pay across 12 graduated state brackets up to 11.0%.",
    taxType: "graduated",
    topRateText: "11.0%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Idaho",
    slug: "idaho",
    abbrev: "ID",
    href: "/tools/idaho-salary-calculator",
    title: "Idaho Salary Calculator",
    description: "Calculate Idaho take-home pay with the flat 5.695% state income tax rate.",
    taxType: "flat",
    topRateText: "5.695%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Illinois",
    slug: "illinois",
    abbrev: "IL",
    href: "/tools/illinois-paycheck-calculator",
    title: "Illinois Paycheck Calculator",
    description: "Calculate Illinois take-home pay after the flat 4.95% state income tax, personal exemptions, and 0% Chicago local wage tax.",
    taxType: "flat",
    topRateText: "4.95%",
    hasIncomeTax: true,
    isLive: true,
    badge: "4.95% Flat",
  },
  {
    name: "Indiana",
    slug: "indiana",
    abbrev: "IN",
    href: "/tools/indiana-salary-calculator",
    title: "Indiana Salary Calculator",
    description: "Calculate Indiana take-home pay after 3.05% flat state income tax and county surtaxes.",
    taxType: "flat",
    topRateText: "3.05%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Iowa",
    slug: "iowa",
    abbrev: "IA",
    href: "/tools/iowa-salary-calculator",
    title: "Iowa Salary Calculator",
    description: "Calculate Iowa take-home pay with the consolidated flat 3.8% state tax rate.",
    taxType: "flat",
    topRateText: "3.8%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Kansas",
    slug: "kansas",
    abbrev: "KS",
    href: "/tools/kansas-salary-calculator",
    title: "Kansas Salary Calculator",
    description: "Calculate Kansas take-home pay after graduated brackets up to 5.7%.",
    taxType: "graduated",
    topRateText: "5.7%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Kentucky",
    slug: "kentucky",
    abbrev: "KY",
    href: "/tools/kentucky-salary-calculator",
    title: "Kentucky Salary Calculator",
    description: "Calculate Kentucky take-home pay after 4.0% flat state tax and city occupational fees.",
    taxType: "flat",
    topRateText: "4.0%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Louisiana",
    slug: "louisiana",
    abbrev: "LA",
    href: "/tools/louisiana-salary-calculator",
    title: "Louisiana Salary Calculator",
    description: "Calculate Louisiana take-home pay across 1.85% to 4.25% state income tax brackets.",
    taxType: "graduated",
    topRateText: "4.25%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Maine",
    slug: "maine",
    abbrev: "ME",
    href: "/tools/maine-salary-calculator",
    title: "Maine Salary Calculator",
    description: "Calculate Maine take-home pay across 5.8% to 7.15% progressive brackets.",
    taxType: "graduated",
    topRateText: "7.15%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Maryland",
    slug: "maryland",
    abbrev: "MD",
    href: "/tools/maryland-salary-calculator",
    title: "Maryland Salary Calculator",
    description: "Calculate Maryland take-home pay with 2.0% to 5.75% state tax plus mandatory county tax.",
    taxType: "graduated",
    topRateText: "5.75%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Massachusetts",
    slug: "massachusetts",
    abbrev: "MA",
    href: "/tools/massachusetts-salary-calculator",
    title: "Massachusetts Salary Calculator",
    description: "Calculate Massachusetts take-home pay with the flat 5.0% rate and millionaire surtax.",
    taxType: "flat",
    topRateText: "9.0%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Michigan",
    slug: "michigan",
    abbrev: "MI",
    href: "/tools/michigan-salary-calculator",
    title: "Michigan Salary Calculator",
    description: "Calculate Michigan take-home pay after 4.25% flat state tax and city income taxes.",
    taxType: "flat",
    topRateText: "4.25%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Minnesota",
    slug: "minnesota",
    abbrev: "MN",
    href: "/tools/minnesota-salary-calculator",
    title: "Minnesota Salary Calculator",
    description: "Calculate Minnesota take-home pay across progressive tiers from 5.35% to 9.85%.",
    taxType: "graduated",
    topRateText: "9.85%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Mississippi",
    slug: "mississippi",
    abbrev: "MS",
    href: "/tools/mississippi-salary-calculator",
    title: "Mississippi Salary Calculator",
    description: "Calculate Mississippi take-home pay with the phased 4.7% flat individual rate.",
    taxType: "flat",
    topRateText: "4.7%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Missouri",
    slug: "missouri",
    abbrev: "MO",
    href: "/tools/missouri-salary-calculator",
    title: "Missouri Salary Calculator",
    description: "Calculate Missouri take-home pay across brackets up to 4.7% and St. Louis/KC city earnings tax.",
    taxType: "graduated",
    topRateText: "4.7%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Montana",
    slug: "montana",
    abbrev: "MT",
    href: "/tools/montana-salary-calculator",
    title: "Montana Salary Calculator",
    description: "Calculate Montana take-home pay after dual 4.7% and 5.9% statutory state tax brackets.",
    taxType: "graduated",
    topRateText: "5.9%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Nebraska",
    slug: "nebraska",
    abbrev: "NE",
    href: "/tools/nebraska-salary-calculator",
    title: "Nebraska Salary Calculator",
    description: "Calculate Nebraska take-home pay across progressive tax rates up to 5.84%.",
    taxType: "graduated",
    topRateText: "5.84%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Nevada",
    slug: "nevada",
    abbrev: "NV",
    href: "/tools/nevada-salary-calculator",
    title: "Nevada Salary Calculator",
    description: "Calculate Nevada take-home pay with 0.0% state personal income tax.",
    taxType: "none",
    topRateText: "0.0%",
    hasIncomeTax: false,
    isLive: false,
  },
  {
    name: "New Hampshire",
    slug: "new-hampshire",
    abbrev: "NH",
    href: "/tools/new-hampshire-salary-calculator",
    title: "New Hampshire Salary Calculator",
    description: "Calculate New Hampshire take-home pay with 0.0% tax on earned employee wages.",
    taxType: "none",
    topRateText: "0.0%",
    hasIncomeTax: false,
    isLive: false,
  },
  {
    name: "New Jersey",
    slug: "new-jersey",
    abbrev: "NJ",
    href: "/tools/new-jersey-salary-calculator",
    title: "New Jersey Salary Calculator",
    description: "Calculate New Jersey take-home pay across 1.4% to 10.75% progressive brackets.",
    taxType: "graduated",
    topRateText: "10.75%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "New Mexico",
    slug: "new-mexico",
    abbrev: "NM",
    href: "/tools/new-mexico-salary-calculator",
    title: "New Mexico Salary Calculator",
    description: "Calculate New Mexico take-home pay across 1.7% to 5.9% graduated income tax tiers.",
    taxType: "graduated",
    topRateText: "5.9%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "New York",
    slug: "new-york",
    abbrev: "NY",
    href: "/tools/new-york-salary-calculator",
    title: "New York Salary Calculator",
    description: "Calculate New York take-home pay after state brackets up to 10.9% and NYC resident local taxes.",
    taxType: "graduated",
    topRateText: "10.9%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "North Carolina",
    slug: "north-carolina",
    abbrev: "NC",
    href: "/tools/north-carolina-salary-calculator",
    title: "North Carolina Salary Calculator",
    description: "Calculate North Carolina take-home pay with the reduced 4.5% flat state income tax rate.",
    taxType: "flat",
    topRateText: "4.5%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "North Dakota",
    slug: "north-dakota",
    abbrev: "ND",
    href: "/tools/north-dakota-salary-calculator",
    title: "North Dakota Salary Calculator",
    description: "Calculate North Dakota take-home pay with 0% to 2.5% marginal tax tiers.",
    taxType: "graduated",
    topRateText: "2.5%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Ohio",
    slug: "ohio",
    abbrev: "OH",
    href: "/tools/ohio-salary-calculator",
    title: "Ohio Salary Calculator",
    description: "Calculate Ohio take-home pay after 2.75% to 3.5% state brackets and municipal income taxes.",
    taxType: "graduated",
    topRateText: "3.5%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Oklahoma",
    slug: "oklahoma",
    abbrev: "OK",
    href: "/tools/oklahoma-salary-calculator",
    title: "Oklahoma Salary Calculator",
    description: "Calculate Oklahoma take-home pay across 0.25% to 4.75% progressive brackets.",
    taxType: "graduated",
    topRateText: "4.75%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Oregon",
    slug: "oregon",
    abbrev: "OR",
    href: "/tools/oregon-salary-calculator",
    title: "Oregon Salary Calculator",
    description: "Calculate Oregon take-home pay after progressive brackets from 4.75% to 9.9%.",
    taxType: "graduated",
    topRateText: "9.9%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Pennsylvania",
    slug: "pennsylvania",
    abbrev: "PA",
    href: "/tools/pennsylvania-salary-calculator",
    title: "Pennsylvania Salary Calculator",
    description: "Calculate Pennsylvania take-home pay after 3.07% flat state tax and local EIT taxes.",
    taxType: "flat",
    topRateText: "3.07%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Rhode Island",
    slug: "rhode-island",
    abbrev: "RI",
    href: "/tools/rhode-island-salary-calculator",
    title: "Rhode Island Salary Calculator",
    description: "Calculate Rhode Island take-home pay across 3.75% to 5.99% graduated tax brackets.",
    taxType: "graduated",
    topRateText: "5.99%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "South Carolina",
    slug: "south-carolina",
    abbrev: "SC",
    href: "/tools/south-carolina-salary-calculator",
    title: "South Carolina Salary Calculator",
    description: "Calculate South Carolina take-home pay across brackets up to 6.4%.",
    taxType: "graduated",
    topRateText: "6.4%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "South Dakota",
    slug: "south-dakota",
    abbrev: "SD",
    href: "/tools/south-dakota-salary-calculator",
    title: "South Dakota Salary Calculator",
    description: "Calculate South Dakota take-home pay with 0.0% state personal wage withholding.",
    taxType: "none",
    topRateText: "0.0%",
    hasIncomeTax: false,
    isLive: false,
  },
  {
    name: "Tennessee",
    slug: "tennessee",
    abbrev: "TN",
    href: "/tools/tennessee-salary-calculator",
    title: "Tennessee Salary Calculator",
    description: "Calculate Tennessee take-home pay with 0.0% state personal earned income tax.",
    taxType: "none",
    topRateText: "0.0%",
    hasIncomeTax: false,
    isLive: false,
  },
  {
    name: "Texas",
    slug: "texas",
    abbrev: "TX",
    href: "/tools/texas-salary-calculator",
    title: "Texas Salary Calculator",
    description: "Calculate Texas take-home pay with 0.0% state personal income tax under the state constitution.",
    taxType: "none",
    topRateText: "0.0%",
    hasIncomeTax: false,
    isLive: false,
  },
  {
    name: "Utah",
    slug: "utah",
    abbrev: "UT",
    href: "/tools/utah-salary-calculator",
    title: "Utah Salary Calculator",
    description: "Calculate Utah take-home pay after the flat 4.55% state individual income tax rate.",
    taxType: "flat",
    topRateText: "4.55%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Vermont",
    slug: "vermont",
    abbrev: "VT",
    href: "/tools/vermont-salary-calculator",
    title: "Vermont Salary Calculator",
    description: "Calculate Vermont take-home pay across 3.35% to 8.75% progressive brackets.",
    taxType: "graduated",
    topRateText: "8.75%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Virginia",
    slug: "virginia",
    abbrev: "VA",
    href: "/tools/virginia-salary-calculator",
    title: "Virginia Salary Calculator",
    description: "Calculate Virginia take-home pay across 2.0% to 5.75% statutory state brackets.",
    taxType: "graduated",
    topRateText: "5.75%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Washington",
    slug: "washington",
    abbrev: "WA",
    href: "/tools/washington-salary-calculator",
    title: "Washington Salary Calculator",
    description: "Calculate Washington take-home pay with 0.0% personal wage withholding.",
    taxType: "none",
    topRateText: "0.0%",
    hasIncomeTax: false,
    isLive: false,
  },
  {
    name: "West Virginia",
    slug: "west-virginia",
    abbrev: "WV",
    href: "/tools/west-virginia-salary-calculator",
    title: "West Virginia Salary Calculator",
    description: "Calculate West Virginia take-home pay across 2.36% to 5.12% progressive brackets.",
    taxType: "graduated",
    topRateText: "5.12%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Wisconsin",
    slug: "wisconsin",
    abbrev: "WI",
    href: "/tools/wisconsin-salary-calculator",
    title: "Wisconsin Salary Calculator",
    description: "Calculate Wisconsin take-home pay across four tax brackets ranging from 3.5% to 7.65%.",
    taxType: "graduated",
    topRateText: "7.65%",
    hasIncomeTax: true,
    isLive: false,
  },
  {
    name: "Wyoming",
    slug: "wyoming",
    abbrev: "WY",
    href: "/tools/wyoming-salary-calculator",
    title: "Wyoming Salary Calculator",
    description: "Calculate Wyoming take-home pay with 0.0% state personal income tax.",
    taxType: "none",
    topRateText: "0.0%",
    hasIncomeTax: false,
    isLive: false,
  },
];

export function getLiveStateCalculators(): StateCalculatorItem[] {
  return STATE_CALCULATORS.filter((s) => s.isLive);
}

export function getAllStateCalculators(): StateCalculatorItem[] {
  return STATE_CALCULATORS;
}

export function getStateCalculator(slug: string): StateCalculatorItem | undefined {
  return STATE_CALCULATORS.find((s) => s.slug === slug);
}
