"use client";

import { useState, useEffect, useMemo, useRef } from "react";
import {
  FastingProtocolId,
  AnchorType,
  PROTOCOLS,
  calculateFastingSchedule,
  getFastingExplanationSteps,
  FastingScheduleResult,
} from "@/lib/calculators/intermittentFasting";
import { generatePdfAsync } from "@/lib/utils/downloadPdf";
import DownloadPdfButton from "@/components/DownloadPdfButton";
import ExplainResultAccordion from "@/components/ExplainResultAccordion";
import ShareResultButton from "@/components/ShareResultButton";
import ShareResultModal from "@/components/ShareResultModal";
import { Clock, Timer, Sparkles, Moon, Utensils, AlertCircle, Info, RefreshCw } from "lucide-react";

export default function IntermittentFastingWidget() {
  const [protocolId, setProtocolId] = useState<FastingProtocolId>("16-8");
  const [customFastHours, setCustomFastHours] = useState<number>(14);
  const [anchorType, setAnchorType] = useState<AnchorType>("eat_start");
  const [anchorTimeStr, setAnchorTimeStr] = useState<string>("12:00");
  const [nowDate, setNowDate] = useState<Date | null>(null);

  const [copied, setCopied] = useState<boolean>(false);
  const [isShareModalOpen, setIsShareModalOpen] = useState<boolean>(false);
  const [isPdfLoading, setIsPdfLoading] = useState<boolean>(false);

  // Live ticking clock effect
  useEffect(() => {
    setNowDate(new Date());
    const interval = setInterval(() => {
      setNowDate(new Date());
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  // Compute live schedule result
  const scheduleResult: FastingScheduleResult | null = useMemo(() => {
    if (!nowDate) return null;
    return calculateFastingSchedule(
      protocolId,
      customFastHours,
      anchorType,
      anchorTimeStr,
      nowDate
    );
  }, [protocolId, customFastHours, anchorType, anchorTimeStr, nowDate]);

  const handleCopy = () => {
    if (!scheduleResult) return;
    const text = [
      `⏱️ Intermittent Fasting Schedule (${scheduleResult.protocolName})`,
      `• Current Phase: ${scheduleResult.currentPhase === "FASTING" ? "Fasting 🌙" : "Eating 🍽️"}`,
      `• Live Countdown: ${scheduleResult.countdownFormatted} remaining until ${scheduleResult.nextPhaseLabel}`,
      `• Fasting Window: ${scheduleResult.fastingStartStr} – ${scheduleResult.fastingEndStr} (${scheduleResult.fastingHours} hrs)`,
      `• Eating Window: ${scheduleResult.eatingStartStr} – ${scheduleResult.eatingEndStr} (${scheduleResult.eatingHours} hrs)`,
      `Calculated on QuickCalc: https://quickcalc.cloud/tools/intermittent-fasting-calculator`,
    ].join("\n");

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleExportTxt = () => {
    if (!scheduleResult) return;
    const text = [
      `INTERMITTENT FASTING SCHEDULE REPORT`,
      `Generated by QuickCalc (https://quickcalc.cloud)`,
      `--------------------------------------------------`,
      `Protocol: ${scheduleResult.protocolName}`,
      `Fasting Window: ${scheduleResult.fastingStartStr} to ${scheduleResult.fastingEndStr} (${scheduleResult.fastingHours} Hours)`,
      `Eating Window: ${scheduleResult.eatingStartStr} to ${scheduleResult.eatingEndStr} (${scheduleResult.eatingHours} Hours)`,
      `Current Status: ${scheduleResult.currentPhase === "FASTING" ? "Fasting Phase 🌙" : "Eating Phase 🍽️"}`,
      `Time Remaining in Current Phase: ${scheduleResult.countdownFormatted}`,
      `Next Phase Transition: ${scheduleResult.nextPhaseLabel} at ${scheduleResult.nextPhaseTimeStr}`,
      `--------------------------------------------------`,
      `Hydration Reminder: Water, plain tea, and black coffee are allowed during fasting hours.`,
    ].join("\n");

    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `fasting-schedule-${scheduleResult.protocolName.replace(/[^a-zA-Z0-9]/g, "-")}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = async () => {
    if (!scheduleResult) return;
    setIsPdfLoading(true);
    try {
      await generatePdfAsync({
        toolName: "Intermittent Fasting Calculator",
        toolSlug: "intermittent-fasting-calculator",
        inputs: [
          { label: "Selected Protocol", value: scheduleResult.protocolName },
          { label: "Anchor Option", value: anchorType === "eat_start" ? "Start of Eating Window" : anchorType === "eat_end" ? "End of Eating Window" : "Start of Fasting Window" },
          { label: "Anchor Time Input", value: scheduleResult.eatingStartStr },
        ],
        results: [
          { label: "Current Active Phase", value: scheduleResult.currentPhase === "FASTING" ? "Fasting Phase 🌙" : "Eating Phase 🍽️", isHighlight: true },
          { label: "Time Remaining in Phase", value: scheduleResult.countdownFormatted, isHighlight: true },
          { label: "Daily Fasting Window", value: `${scheduleResult.fastingStartStr} – ${scheduleResult.fastingEndStr} (${scheduleResult.fastingHours} hrs)` },
          { label: "Daily Eating Window", value: `${scheduleResult.eatingStartStr} – ${scheduleResult.eatingEndStr} (${scheduleResult.eatingHours} hrs)` },
        ],
        summaryNote: `Stay hydrated during fasting hours with water, black coffee, or plain unflavored tea.`,
        table: {
          title: "Complete 24-Hour Schedule Breakdown",
          headers: ["Phase", "Duration", "Daily Window Times"],
          rows: [
            ["Fasting Window", `${scheduleResult.fastingHours} Hours`, `${scheduleResult.fastingStartStr} to ${scheduleResult.fastingEndStr}`],
            ["Eating Window", `${scheduleResult.eatingHours} Hours`, `${scheduleResult.eatingStartStr} to ${scheduleResult.eatingEndStr}`],
            ["Next Transition", `In ${scheduleResult.countdownFormatted}`, `${scheduleResult.nextPhaseLabel} at ${scheduleResult.nextPhaseTimeStr}`],
          ],
        },
        filename: `Intermittent-Fasting-Schedule.pdf`,
      });
    } finally {
      setIsPdfLoading(false);
    }
  };

  const explanationSteps = useMemo(() => {
    if (!scheduleResult) return [];
    return getFastingExplanationSteps(scheduleResult);
  }, [scheduleResult]);

  return (
    <div className="w-full max-w-2xl mx-auto bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl shadow-xl overflow-hidden my-6 transition-all">
      {/* Tool Input Header & Presets */}
      <div className="p-4 sm:p-6 space-y-6 border-b border-zinc-200 dark:border-zinc-800 bg-zinc-50/50 dark:bg-zinc-950/30">
        
        {/* Protocol Selector Tabs */}
        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400 mb-3">
            1. Select Fasting Protocol
          </label>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
            {PROTOCOLS.map((p) => {
              const isActive = protocolId === p.id;
              return (
                <button
                  key={p.id}
                  type="button"
                  onClick={() => setProtocolId(p.id)}
                  className={`py-2.5 px-3 rounded-xl font-bold text-xs sm:text-sm transition-all duration-200 flex flex-col items-center justify-center gap-0.5 border ${
                    isActive
                      ? "bg-teal-600 dark:bg-teal-500 text-white border-teal-600 dark:border-teal-500 shadow-md shadow-teal-500/20 scale-[1.02]"
                      : "bg-white dark:bg-zinc-800/80 text-zinc-700 dark:text-zinc-300 border-zinc-200 dark:border-zinc-700 hover:border-teal-400 dark:hover:border-teal-500 hover:bg-teal-50/50 dark:hover:bg-teal-950/20"
                  }`}
                >
                  <span>{p.name}</span>
                  <span className={`text-[10px] font-normal ${isActive ? "text-teal-100" : "text-zinc-500 dark:text-zinc-400"}`}>
                    {p.id === "custom" ? `${customFastHours}:${24 - customFastHours}` : `${p.fastingHours}:${p.eatingHours}`}
                  </span>
                </button>
              );
            })}
          </div>
          
          {/* Custom Protocol Options */}
          {protocolId === "custom" && (
            <div className="mt-4 p-3.5 bg-white dark:bg-zinc-800/90 rounded-xl border border-zinc-200 dark:border-zinc-700 space-y-2 animate-fade-in">
              <div className="flex justify-between items-center text-xs font-semibold text-zinc-700 dark:text-zinc-300">
                <span>Fasting Duration: <strong className="text-teal-600 dark:text-teal-400">{customFastHours} Hours</strong></span>
                <span>Eating Duration: <strong className="text-emerald-600 dark:text-emerald-400">{24 - customFastHours} Hours</strong></span>
              </div>
              <input
                type="range"
                min="1"
                max="23"
                value={customFastHours}
                onChange={(e) => setCustomFastHours(parseInt(e.target.value, 10))}
                className="w-full h-2 bg-zinc-200 dark:bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-teal-600 dark:accent-teal-400"
              />
              <div className="flex justify-between text-[10px] text-zinc-400">
                <span>1h Fast</span>
                <span>12h Fast</span>
                <span>23h Fast</span>
              </div>
            </div>
          )}
        </div>

        {/* Anchor Time Selection */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label htmlFor="anchorType" className="block text-xs font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400 mb-2">
              2. Timing Anchor
            </label>
            <select
              id="anchorType"
              value={anchorType}
              onChange={(e) => setAnchorType(e.target.value as AnchorType)}
              className="w-full rounded-xl border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-800 px-3.5 py-2.5 text-xs sm:text-sm font-medium text-zinc-900 dark:text-white focus:border-teal-500 focus:outline-none focus:ring-1 focus:ring-teal-500 shadow-sm"
            >
              <option value="eat_start">🍽️ When do you start eating?</option>
              <option value="eat_end">🚪 When do you finish eating?</option>
              <option value="fast_start">🌙 When do you start your fast?</option>
            </select>
          </div>

          <div>
            <label htmlFor="anchorTime" className="block text-xs font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400 mb-2">
              3. Select Time
            </label>
            <div className="flex rounded-xl shadow-sm">
              <input
                type="time"
                id="anchorTime"
                value={anchorTimeStr}
                onChange={(e) => setAnchorTimeStr(e.target.value)}
                className="block w-full rounded-xl border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-800 px-3.5 py-2.5 text-xs sm:text-sm font-semibold text-zinc-900 dark:text-white focus:border-teal-500 focus:outline-none focus:ring-1 focus:ring-teal-500"
              />
            </div>
          </div>
        </div>

        {/* Quick Time Preset Chips */}
        <div className="flex items-center gap-1.5 flex-wrap">
          <span className="text-[11px] text-zinc-400 font-medium mr-1">Quick set:</span>
          {["08:00", "12:00", "13:00", "20:00"].map((t) => {
            const label = t === "08:00" ? "8:00 AM" : t === "12:00" ? "12:00 PM" : t === "13:00" ? "1:00 PM" : "8:00 PM";
            return (
              <button
                key={t}
                type="button"
                onClick={() => setAnchorTimeStr(t)}
                className={`px-2.5 py-1 rounded-lg text-xs font-medium transition-colors border ${
                  anchorTimeStr === t
                    ? "bg-teal-50 dark:bg-teal-950/40 text-teal-700 dark:text-teal-300 border-teal-300 dark:border-teal-700"
                    : "bg-white dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 border-zinc-200 dark:border-zinc-700 hover:bg-zinc-100 dark:hover:bg-zinc-700"
                }`}
              >
                {label}
              </button>
            );
          })}
        </div>
      </div>

      {/* Main Results Container */}
      <div className="p-4 sm:p-6 space-y-6">
        {scheduleResult ? (
          <div className="space-y-6">
            
            {/* HERO LIVE COUNTDOWN CARD */}
            <div className={`p-5 sm:p-6 rounded-2xl border transition-all shadow-sm ${
              scheduleResult.currentPhase === "FASTING"
                ? "bg-gradient-to-br from-indigo-950/90 via-slate-900 to-indigo-900 text-white border-indigo-700/50 shadow-indigo-950/20"
                : "bg-gradient-to-br from-emerald-950/90 via-zinc-900 to-teal-900 text-white border-emerald-700/50 shadow-emerald-950/20"
            }`}>
              
              {/* Top Status Badge & Real-Time Indicator */}
              <div className="flex flex-wrap items-center justify-between gap-2 mb-3">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-extrabold tracking-wide uppercase bg-white/10 backdrop-blur-md border border-white/20">
                  {scheduleResult.currentPhase === "FASTING" ? (
                    <>
                      <Moon size={14} className="text-indigo-300 animate-pulse" />
                      <span className="text-indigo-200">Fasting Phase Active</span>
                    </>
                  ) : (
                    <>
                      <Utensils size={14} className="text-emerald-300 animate-pulse" />
                      <span className="text-emerald-200">Eating Phase Active</span>
                    </>
                  )}
                </div>

                <div className="inline-flex items-center gap-1.5 text-[11px] text-white/70 font-medium">
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping"></span>
                  <span>Live Ticking</span>
                </div>
              </div>

              {/* Countdown Ticking Display */}
              <div className="my-3 text-center sm:text-left">
                <span className="text-xs uppercase tracking-wider text-white/70 font-semibold block mb-1">
                  Time Remaining Until {scheduleResult.nextPhaseLabel}
                </span>
                <div className="font-mono text-4xl sm:text-5xl font-extrabold tracking-wider tabular-nums text-white drop-shadow-md">
                  {scheduleResult.countdownFormatted}
                </div>
                <div className="text-xs text-white/80 mt-1 font-medium">
                  Next transition at <strong className="text-white font-bold">{scheduleResult.nextPhaseTimeStr}</strong>
                </div>
              </div>

              {/* Current Phase Progress Bar */}
              <div className="space-y-1.5 mt-4 pt-3 border-t border-white/10">
                <div className="flex justify-between text-xs text-white/80 font-medium">
                  <span>Current Phase Progress</span>
                  <span className="font-bold text-white">{Math.round(scheduleResult.progressPercent)}%</span>
                </div>
                <div className="h-2.5 w-full rounded-full bg-white/15 overflow-hidden p-0.5">
                  <div
                    className={`h-full rounded-full transition-all duration-1000 ${
                      scheduleResult.currentPhase === "FASTING"
                        ? "bg-indigo-400 shadow-[0_0_8px_rgba(129,140,248,0.8)]"
                        : "bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.8)]"
                    }`}
                    style={{ width: `${scheduleResult.progressPercent}%` }}
                  ></div>
                </div>
              </div>
            </div>

            {/* 24-HOUR VISUAL TIMELINE GAUGE BAR */}
            <div className="p-4 sm:p-5 bg-zinc-50 dark:bg-zinc-950/50 border border-zinc-200 dark:border-zinc-800 rounded-2xl space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Timer size={16} className="text-teal-600 dark:text-teal-400" />
                  <span className="text-xs font-bold uppercase tracking-wider text-zinc-900 dark:text-zinc-100">
                    24-Hour Daily Timeline Visual
                  </span>
                </div>
                <span className="text-xs font-semibold text-zinc-500 dark:text-zinc-400">
                  Current Time: <strong className="text-zinc-900 dark:text-white font-mono">{scheduleResult.nowTimeFormatted}</strong>
                </span>
              </div>

              {/* Segmented Timeline Bar */}
              <div className="relative h-8 w-full rounded-xl bg-zinc-200 dark:bg-zinc-800 overflow-hidden flex shadow-inner border border-zinc-300 dark:border-zinc-700">
                {scheduleResult.timelineSegments.map((segment, idx) => (
                  <div
                    key={idx}
                    title={segment.label}
                    style={{ width: `${segment.widthPercent}%` }}
                    className={`h-full transition-all flex items-center justify-center text-[10px] font-bold text-white tracking-tight ${
                      segment.type === "FASTING"
                        ? "bg-indigo-600 dark:bg-indigo-500 opacity-90"
                        : "bg-emerald-500 dark:bg-emerald-400 opacity-90"
                    }`}
                  >
                    {segment.widthPercent > 12 && (
                      <span>{segment.type === "FASTING" ? "🌙 Fast" : "🍽️ Eat"}</span>
                    )}
                  </div>
                ))}

                {/* NOW Needle / Pin Marker */}
                <div
                  className="absolute top-0 bottom-0 w-1 bg-zinc-950 dark:bg-white shadow-[0_0_10px_rgba(0,0,0,0.8)] transition-all duration-500 z-10 flex flex-col items-center justify-between"
                  style={{ left: `${scheduleResult.nowPercent}%` }}
                >
                  <div className="w-2.5 h-2.5 rounded-full bg-rose-500 border border-white -mt-1 shadow-sm animate-pulse"></div>
                  <div className="w-2.5 h-2.5 rounded-full bg-rose-500 border border-white -mb-1 shadow-sm"></div>
                </div>
              </div>

              {/* Hour Scale Markers */}
              <div className="flex justify-between text-[10px] font-semibold text-zinc-400 dark:text-zinc-500 px-0.5 font-mono">
                <span>12 AM</span>
                <span>4 AM</span>
                <span>8 AM</span>
                <span>12 PM</span>
                <span>4 PM</span>
                <span>8 PM</span>
                <span>12 AM</span>
              </div>

              {/* Legend & Window Badges */}
              <div className="grid grid-cols-2 gap-3 pt-2">
                <div className="p-3 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl flex items-center gap-3">
                  <div className="w-3 h-8 rounded-md bg-indigo-600 dark:bg-indigo-500 shrink-0"></div>
                  <div>
                    <span className="text-[11px] text-zinc-500 dark:text-zinc-400 font-medium block">
                      Fasting Window ({scheduleResult.fastingHours}h)
                    </span>
                    <span className="text-xs font-bold text-zinc-900 dark:text-white font-mono">
                      {scheduleResult.fastingStartStr} – {scheduleResult.fastingEndStr}
                    </span>
                  </div>
                </div>

                <div className="p-3 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl flex items-center gap-3">
                  <div className="w-3 h-8 rounded-md bg-emerald-500 dark:bg-emerald-400 shrink-0"></div>
                  <div>
                    <span className="text-[11px] text-zinc-500 dark:text-zinc-400 font-medium block">
                      Eating Window ({scheduleResult.eatingHours}h)
                    </span>
                    <span className="text-xs font-bold text-zinc-900 dark:text-white font-mono">
                      {scheduleResult.eatingStartStr} – {scheduleResult.eatingEndStr}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* EXPORT & ACTION BUTTONS */}
            <div className="flex flex-wrap items-center justify-between gap-2.5 pt-2 border-t border-zinc-200 dark:border-zinc-800">
              <button
                type="button"
                onClick={handleCopy}
                className="flex items-center gap-2 text-xs font-semibold text-zinc-700 dark:text-zinc-300 hover:text-teal-600 dark:hover:text-teal-400 transition-all duration-200 hover:scale-[1.02] bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 px-3.5 py-2 rounded-xl shadow-sm focus:ring-1 focus:ring-teal-500 focus:outline-none"
              >
                {copied ? "✅ Copied Schedule!" : "📋 Copy Summary"}
              </button>

              <div className="flex flex-wrap items-center gap-2">
                <ShareResultButton onClick={() => setIsShareModalOpen(true)} />
                <button
                  type="button"
                  onClick={handleExportTxt}
                  className="flex items-center gap-2 text-xs font-semibold text-teal-600 dark:text-teal-400 hover:text-teal-700 dark:hover:text-teal-300 transition-all duration-200 hover:scale-[1.02] bg-teal-50 dark:bg-teal-950/30 px-3.5 py-2 rounded-xl shadow-sm border border-teal-200/50 dark:border-teal-800/50 focus:ring-1 focus:ring-teal-500 focus:outline-none"
                >
                  📥 Export TXT
                </button>
                <DownloadPdfButton onClick={handleDownloadPdf} isGenerating={isPdfLoading} />
              </div>
            </div>

            {/* STEP-BY-STEP EXPLANATION ACCORDION */}
            <ExplainResultAccordion steps={explanationSteps} />

            {/* BRIEF NON-ALARMIST MEDICAL DISCLAIMER NOTE */}
            <div className="p-4 bg-amber-50/70 dark:bg-amber-950/30 border border-amber-200/80 dark:border-amber-900/40 rounded-xl text-xs text-amber-900 dark:text-amber-200 flex items-start gap-3">
              <AlertCircle size={18} className="text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
              <div className="leading-relaxed">
                <strong className="font-bold text-amber-950 dark:text-amber-100 block mb-0.5">
                  General Timing Note & Health Considerations
                </strong>
                This Intermittent Fasting Calculator is a scheduling utility for general reference only. Intermittent fasting is not medical advice and is not appropriate for everyone, including pregnant or nursing individuals, children, or people with a history of eating disorders or specific medical conditions (such as diabetes). Always consult a healthcare professional before altering your eating pattern.
              </div>
            </div>

          </div>
        ) : (
          <div className="p-8 text-center text-zinc-500 animate-pulse">
            Calculating fasting timeline...
          </div>
        )}
      </div>

      {/* SHARE RESULT MODAL */}
      {scheduleResult && (
        <ShareResultModal
          isOpen={isShareModalOpen}
          onClose={() => setIsShareModalOpen(false)}
          data={{
            toolName: "Intermittent Fasting Calculator",
            toolSlug: "intermittent-fasting-calculator",
            category: "Health & Fitness",
            resultValue: scheduleResult.countdownFormatted,
            resultLabel: `Remaining until ${scheduleResult.nextPhaseLabel} (${scheduleResult.protocolName})`,
            inputsSummary: [
              { label: "Protocol", value: scheduleResult.protocolName },
              { label: "Fasting Window", value: `${scheduleResult.fastingStartStr} – ${scheduleResult.fastingEndStr}` },
              { label: "Eating Window", value: `${scheduleResult.eatingStartStr} – ${scheduleResult.eatingEndStr}` },
              { label: "Active Phase", value: scheduleResult.currentPhase === "FASTING" ? "Fasting 🌙" : "Eating 🍽️" },
            ],
            queryParams: {
              p: protocolId,
              cf: customFastHours.toString(),
              a: anchorType,
              t: anchorTimeStr,
            },
          }}
        />
      )}
    </div>
  );
}
